$kind: http-request
name: GET /api/catalog/health
url: "{{traefik_url}}/api/catalog/health"
method: GET
scripts:
  - type: afterResponse
    code: |-
      pm.test('Status 200', () => pm.response.to.have.status(200));
      pm.test('Proxied to catalog', () => pm.expect(pm.response.json().service).to.eql('service-catalog'));
    language: text/javascript
order: 2000
